### ISSUE TITLE
运行分析脚本raphael.py 报错

### ISSUE THREAD

**Issue by winchances** [bytedance/memory-leak-detector#6]
Raphael script version: 1.0.0
Traceback (most recent call last):
  File "library/src/main/python/raphael.py", line 215, in <module>
    report = parse_report(string)
  File "library/src/main/python/raphael.py", line 183, in parse_report
    report.append(Trace(match[0][0], match[0][1], match[0][2], stack))
IndexError: list index out of range

**Comment by shentianzhou** [comment]
必现的吗？应该是生成的原始日志格式有问题，方便提攻以下儿原始日志吗？

**Comment by XWayne** [comment]
我这边出现同样的问题：
python library/src/main/python/raphael.py -r report
Raphael script version: 1.0.0
Traceback (most recent call last):
  File "library/src/main/python/raphael.py", line 215, in <module>
    report = parse_report(string)
  File "library/src/main/python/raphael.py", line 183, in parse_report
    report.append(Trace(match[0][0], match[0][1], match[0][2], stack))
IndexError: list index out of range


这是report文件
[report.zip](https://github.com/bytedance/memory-leak-detector/files/6398054/report.zip)

**Comment by shentianzhou** [comment]
格式兼容错误，已修复
